In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [8]:
ride_csv= "raw_data/ride_data.csv"
city_csv= "raw_data/city_data.csv"

In [9]:
ride_df = pd.read_csv(ride_csv)
city_df = pd.read_csv(city_csv)

In [11]:
data = pd.merge(ride_df,city_df, on='city', how='outer')

In [12]:
unique_cities = data["city"].unique()
test = pd.DataFrame(unique_cities).reset_index()

test

     index                     0
0        0              Sarabury
1        1             South Roy
2        2           Wiseborough
3        3           Spencertown
4        4            Nguyenbury
5        5           New Jeffrey
6        6         Port Johnstad
7        7             Jacobfort
8        8           Travisville
9        9            Sandymouth
10      10       New Andreamouth
11      11         New Christine
12      12           Stewartview
13      13        Rodriguezburgh
14      14      West Sydneyhaven
15      15           Swansonbury
16      16              Lisatown
17      17             East Erin
18      18       Port Martinberg
19      19           Edwardsbury
20      20           Pamelahaven
21      21            Fosterside
22      22           West Alexis
23      23           Carrollfort
24      24             New David
25      25          Williamshire
26      26           Torresshire
27      27             New Aaron
28      28            Kelseyland
29      29        Lake Sarashire
..     ...                   ...
95      95             West Evan
96      96             Sarahview
97      97        South Jennifer
98      98            Floresberg
99      99        Williamchester
100    100           Martinmouth
101    101          Port Guytown
102    102      New Cindyborough
103    103      New Michelleberg
104    104       North Tracyfort
105    105            Tiffanyton
106    106       East Cherylfurt
107    107             Horneland
108    108             Kinghaven
109    109          New Johnbury
110    110          South Joseph
111    111          Kennethburgh
112    112          East Stephen
113    113           Stevensport
114    114        West Kevintown
115    115         East Troybury
116    116              Erikport
117    117        Hernandezshire
118    118           Jacksonfort
119    119           East Leslie
120    120         North Whitney
121    121         Manuelchester
122    122           Shelbyhaven
123    123  South Elizabethmouth
124    124           Matthewside

[125 rows x 2 columns]

In [14]:
new_df = pd.merge(data,test,left_on='city', right_on=0, how='left')
new_df2 = new_df.rename(columns={0: "city",'index': 'city id'})
new_df2['city id'] = new_df2['city id'] + 101
new_df2
#disregard cells after t

,city,date,fare,ride_id,driver_count,type,city id,city
0,Sarabury,2016-01-16 13:49:27,38.35,5403689035038,46,Urban,101,Sarabury
1,Sarabury,2016-07-23 07:42:44,21.76,7546681945283,46,Urban,101,Sarabury
2,Sarabury,2016-04-02 04:32:25,38.03,4932495851866,46,Urban,101,Sarabury
3,Sarabury,2016-06-23 05:03:41,26.82,6711035373406,46,Urban,101,Sarabury
4,Sarabury,2016-09-30 12:48:34,30.30,6388737278232,46,Urban,101,Sarabury
5,Sarabury,2016-08-04 00:25:52,27.20,2429366407526,46,Urban,101,Sarabury
6,Sarabury,2016-07-25 10:44:01,17.73,4467299640441,46,Urban,101,Sarabury
7,Sarabury,2016-06-22 16:24:01,23.94,6153395712431,46,Urban,101,Sarabury
8,Sarabury,2016-01-27 17:46:45,16.39,8220809448298,46,Urban,101,Sarabury
9,Sarabury,2016-04-26 11:31:30,21.80,5969441875705,46,Urban,101,Sarabury
10,Sarabury,2016-08-14 19:56:59,7.83,4979570237054,46,Urban,101,Sarabury
11,Sarabury,2016-01-06 03:02:55,5.19,9988466326333,46,Urban,101,Sarabury
12,Sarabury,2016-03-29 15:47:35,17.00,3574423871181,46,Urban,101,Sarabury
13,Sarabury,2016-11-20 11:44:23,28.47,3793266633941,46,Urban,101,Sarabury
14,Sarabury,2016-07-17 20:41:06,17.79,9661023488490,46,Urban,101,Sarabury
15,Sarabury,2016-11-06 02:23:59,19.48,7305651789766,46,Urban,101,Sarabury
16,Sarabury,2016-09-26 07:30:31,26.71,6310253827816,46,Urban,101,Sarabury
17,Sarabury,2016-06-04 20:50:52,14.19,8765571028809,46,Urban,101,Sarabury
18,Sarabury,2016-01-22 23:12:06,38.40,1176229756048,46,Urban,101,Sarabury
19,Sarabury,2016-03-29 19:07:55,20.56,7019491956393,46,Urban,101,Sarabury
20,Sarabury,2016-10-18 04:33:23,37.50,1054393799736,46,Urban,101,Sarabury
21,Sarabury,2016-09-30 20:41:18,44.32,2103508227691,46,Urban,101,Sarabury
22,Sarabury,2016-07-30 10:37:38,25.99,5233926699781,46,Urban,101,Sarabury
23,Sarabury,2016-04-01 07:15:24,6.94,1931215121299,46,Urban,101,Sarabury
24,Sarabury,2016-11-23 03:08:59,37.17,9141412183460,46,Urban,101,Sarabury
25,Sarabury,2016-10-23 02:40:28,17.23,1977978528067,46,Urban,101,Sarabury
26,Sarabury,2016-04-06 21:02:54,7.14,6096364843852,46,Urban,101,Sarabury
27,South Roy,2016-01-02 18:42:34,17.49,4036272335942,35,Urban,102,South Roy
28,South Roy,2016-12-03 08:39:02,32.88,7098916182845,35,Urban,102,South Roy
29,South Roy,2016-11-20 02:09:58,6.81,6512612750531,35,Urban,102,South Roy
...,...,...,...,...,...,...,...,...
2377,East Leslie,2016-11-28 09:09:15,37.76,804829686137,9,Rural,220,East Leslie
2378,East Leslie,2016-09-08 19:19:38,30.59,8211833105097,9,Rural,220,East Leslie
2379,East Leslie,2016-03-02 22:09:34,36.61,5500269118478,9,Rural,220,East Leslie
2380,East Leslie,2016-06-22 07:45:30,34.54,684950063164,9,Rural,220,East Leslie
2381,North Whitney,2016-04-01 21:21:37,51.01,612689673941,10,Rural,221,North Whitney
2382,North Whitney,2016-04-26 09:35:48,42.09,9465134041656,10,Rural,221,North Whitney
2383,North Whitney,2016-06-24 21:09:09,50.03,9224879345166,10,Rural,221,North Whitney
2384,North Whitney,2016-06-10 18:27:03,29.25,4071225680519,10,Rural,221,North Whitney
2385,North Whitney,2016-02-21 18:20:14,42.01,3306522110065,10,Rural,221,North Whitney
2386,North Whitney,2016-11-14 10:46:11,55.07,8000095653619,10,Rural,221,North Whitney
2387,North Whitney,2016-01-24 09:14:51,24.37,7069044920500,10,Rural,221,North Whitney
2388,North Whitney,2016-03-24 10:27:00,29.72,3818227780479,10,Rural,221,North Whitney
2389,North Whitney,2016-11-11 16:24:16,22.99,3454326063039,10,Rural,221,North Whitney
2390,North Whitney,2016-01-26 01:06:41,34.92,4165974278063,10,Rural,221,North Whitney
2391,Manuelchester,2016-03-21 22:15:25,49.62,6045427401799,7,Rural,222,Manuelchester
2392,Shelbyhaven,2016-05-24 15:29:59,18.11,1144791937271,9,Rural,223,Shelbyhaven
2393,Shelbyhaven,2016-10-17 14:47:38,53.42,8515375903761,9,Rural,223,Shelbyhaven
2394,Shelbyhaven,2016-04-21 19:22:03,37.19,5142074323359,9,Rural,223,Shelbyhaven
2395,Shelbyhaven,2016-06-12 16:57:25,30.18,2015025942653,9,Rural,223,Shelbyhaven
2396,Shelbyhaven,2016-07-22 05:59:01,10.64,1406024986969,9,Rural,223,Shelbyhaven
2397,Shelbyhaven,2016-01-25 01:39:16,59.43,8088329954312,9,Rural,223,Shelbyhaven
2398,South Elizabethmouth,2016-04-03 11:13:07,22.79,8193837300497,3,Rural,224,South Elizabethmouth
2399,South Elizabethmouth,2016-03-11 12:27:01,26.72,4943246873754,3,Rural,224,South Elizabethmouth
2400,South Elizabethmouth,2016-11-23 07:47:18,46.39,1939838068038,3,Rural,224,South Elizabethmouth
2401,South Elizabethmouth,2016-07-19 09:35:59,31.09,2959749591417,3,Rural,224,South Elizabethmouth
2402,South Elizabethmouth,2016-04-21 10:20:09,16.50,5702608059064,3,Rural,224,South Elizabethmouth
2403,Matthewside,2016-02-23 17:46:29,59.65,241191157535,4,Rural,225,Matthewside
2404,Matthewside,2016-02-23 00:43:51,40.84,8665248512368,4,Rural,225,Matthewside
2405,Matthewside,2016-05-18 02:00:30,48.67,2049161404256,4,Rural,225,Matthewside
2406,Matthewside,2016-08-08 14:02:35,24.97,2872494724827,4,Rural,225,Matthewside

In [15]:
total_rides= data.fare.count()
avg_fare= (data.fare.sum() / total_rides)
total_rides 

# avg_fare_by_city

2407

In [16]:
sum_it_up['city id'].astype('str')

NameError: name 'sum_it_up' is not defined