In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import csv

#import csvs
ride_csv= "raw_data/ride_data.csv"
city_csv= "raw_data/city_data.csv"

#read csvs into df
ride_df = pd.read_csv(ride_csv)
city_df = pd.read_csv(city_csv)

#merge dataframes
data = pd.merge(ride_df,city_df, on='city', how='outer')

In [2]:
data = data.set_index('city')
data

,date,fare,ride_id,driver_count,type
city,,,,,
Sarabury,2016-01-16 13:49:27,38.35,5403689035038,46,Urban
Sarabury,2016-07-23 07:42:44,21.76,7546681945283,46,Urban
Sarabury,2016-04-02 04:32:25,38.03,4932495851866,46,Urban
Sarabury,2016-06-23 05:03:41,26.82,6711035373406,46,Urban
Sarabury,2016-09-30 12:48:34,30.30,6388737278232,46,Urban
Sarabury,2016-08-04 00:25:52,27.20,2429366407526,46,Urban
Sarabury,2016-07-25 10:44:01,17.73,4467299640441,46,Urban
Sarabury,2016-06-22 16:24:01,23.94,6153395712431,46,Urban
Sarabury,2016-01-27 17:46:45,16.39,8220809448298,46,Urban
Sarabury,2016-04-26 11:31:30,21.80,5969441875705,46,Urban
Sarabury,2016-08-14 19:56:59,7.83,4979570237054,46,Urban
Sarabury,2016-01-06 03:02:55,5.19,9988466326333,46,Urban
Sarabury,2016-03-29 15:47:35,17.00,3574423871181,46,Urban
Sarabury,2016-11-20 11:44:23,28.47,3793266633941,46,Urban
Sarabury,2016-07-17 20:41:06,17.79,9661023488490,46,Urban
Sarabury,2016-11-06 02:23:59,19.48,7305651789766,46,Urban
Sarabury,2016-09-26 07:30:31,26.71,6310253827816,46,Urban
Sarabury,2016-06-04 20:50:52,14.19,8765571028809,46,Urban
Sarabury,2016-01-22 23:12:06,38.40,1176229756048,46,Urban
Sarabury,2016-03-29 19:07:55,20.56,7019491956393,46,Urban
Sarabury,2016-10-18 04:33:23,37.50,1054393799736,46,Urban
Sarabury,2016-09-30 20:41:18,44.32,2103508227691,46,Urban
Sarabury,2016-07-30 10:37:38,25.99,5233926699781,46,Urban
Sarabury,2016-04-01 07:15:24,6.94,1931215121299,46,Urban
Sarabury,2016-11-23 03:08:59,37.17,9141412183460,46,Urban
Sarabury,2016-10-23 02:40:28,17.23,1977978528067,46,Urban
Sarabury,2016-04-06 21:02:54,7.14,6096364843852,46,Urban
South Roy,2016-01-02 18:42:34,17.49,4036272335942,35,Urban
South Roy,2016-12-03 08:39:02,32.88,7098916182845,35,Urban
South Roy,2016-11-20 02:09:58,6.81,6512612750531,35,Urban
...,...,...,...,...,...
East Leslie,2016-11-28 09:09:15,37.76,804829686137,9,Rural
East Leslie,2016-09-08 19:19:38,30.59,8211833105097,9,Rural
East Leslie,2016-03-02 22:09:34,36.61,5500269118478,9,Rural
East Leslie,2016-06-22 07:45:30,34.54,684950063164,9,Rural
North Whitney,2016-04-01 21:21:37,51.01,612689673941,10,Rural
North Whitney,2016-04-26 09:35:48,42.09,9465134041656,10,Rural
North Whitney,2016-06-24 21:09:09,50.03,9224879345166,10,Rural
North Whitney,2016-06-10 18:27:03,29.25,4071225680519,10,Rural
North Whitney,2016-02-21 18:20:14,42.01,3306522110065,10,Rural
North Whitney,2016-11-14 10:46:11,55.07,8000095653619,10,Rural
North Whitney,2016-01-24 09:14:51,24.37,7069044920500,10,Rural
North Whitney,2016-03-24 10:27:00,29.72,3818227780479,10,Rural
North Whitney,2016-11-11 16:24:16,22.99,3454326063039,10,Rural
North Whitney,2016-01-26 01:06:41,34.92,4165974278063,10,Rural
Manuelchester,2016-03-21 22:15:25,49.62,6045427401799,7,Rural
Shelbyhaven,2016-05-24 15:29:59,18.11,1144791937271,9,Rural
Shelbyhaven,2016-10-17 14:47:38,53.42,8515375903761,9,Rural
Shelbyhaven,2016-04-21 19:22:03,37.19,5142074323359,9,Rural
Shelbyhaven,2016-06-12 16:57:25,30.18,2015025942653,9,Rural
Shelbyhaven,2016-07-22 05:59:01,10.64,1406024986969,9,Rural
Shelbyhaven,2016-01-25 01:39:16,59.43,8088329954312,9,Rural
South Elizabethmouth,2016-04-03 11:13:07,22.79,8193837300497,3,Rural
South Elizabethmouth,2016-03-11 12:27:01,26.72,4943246873754,3,Rural
South Elizabethmouth,2016-11-23 07:47:18,46.39,1939838068038,3,Rural
South Elizabethmouth,2016-07-19 09:35:59,31.09,2959749591417,3,Rural
South Elizabethmouth,2016-04-21 10:20:09,16.50,5702608059064,3,Rural
Matthewside,2016-02-23 17:46:29,59.65,241191157535,4,Rural
Matthewside,2016-02-23 00:43:51,40.84,8665248512368,4,Rural
Matthewside,2016-05-18 02:00:30,48.67,2049161404256,4,Rural
Matthewside,2016-08-08 14:02:35,24.97,2872494724827,4,Rural

In [3]:
# Create the GroupBy object based on the "city column
fare_by_city = data.groupby(["city"])

# Calculate averages for fares from each city using the .mean() method
fare_by_city.mean()

                           fare       ride_id  driver_count
city
Alvarezhaven          23.928710  5.351586e+12          21.0
Alyssaberg            20.609615  3.536678e+12          67.0
Anitamouth            37.315556  4.195870e+12          16.0
Antoniomouth          23.625000  5.086800e+12          21.0
Aprilchester          21.981579  4.574788e+12          49.0
Arnoldview            25.106452  5.021952e+12          41.0
Campbellport          33.711333  5.805424e+12          26.0
Carrollbury           36.606000  4.274615e+12           4.0
Carrollfort           25.395517  4.759008e+12          55.0
Clarkstad             31.051667  6.682745e+12          21.0
Conwaymouth           34.591818  4.391649e+12          18.0
Davidtown             22.978095  5.850005e+12          73.0
Davistown             21.497200  4.361977e+12          25.0
East Cherylfurt       31.416154  3.981187e+12           9.0
East Douglas          26.169091  4.732315e+12          12.0
East Erin             24.478214  5.226259e+12          43.0
East Jenniferchester  32.599474  5.933107e+12          22.0
East Leslie           33.660909  6.051052e+12           9.0
East Stephen          39.053000  5.306327e+12           6.0
East Troybury         33.244286  5.948234e+12           3.0
Edwardsbury           26.876667  5.296117e+12          11.0
Erikport              30.043750  6.883015e+12           3.0
Eriktown              25.478947  4.113171e+12          15.0
Floresberg            32.310000  2.630319e+12           7.0
Fosterside            23.034583  5.101131e+12          69.0
Hernandezshire        32.002222  5.206210e+12          10.0
Horneland             21.482500  5.351789e+12           8.0
Jacksonfort           32.006667  4.610855e+12           6.0
Jacobfort             24.779355  4.099091e+12          52.0
Jasonfort             27.831667  6.439182e+12          25.0
...                         ...           ...           ...
South Roy             26.031364  4.862249e+12          35.0
South Shannonborough  26.516667  4.824875e+12           9.0
Spencertown           23.681154  4.850559e+12          68.0
Stevensport           31.948000  3.125721e+12           6.0
Stewartview           21.614000  4.936695e+12          49.0
Swansonbury           27.464706  4.443028e+12          64.0
Thomastown            30.308333  4.525633e+12           1.0
Tiffanyton            28.510000  4.968458e+12          21.0
Torresshire           24.207308  5.117907e+12          70.0
Travisville           27.220870  3.317507e+12          37.0
Vickimouth            21.474667  4.242738e+12          13.0
Webstertown           29.721250  4.401465e+12          26.0
West Alexis           19.523000  5.133766e+12          47.0
West Brandy           24.157667  4.673435e+12          12.0
West Brittanyton      25.436250  5.796976e+12           9.0
West Dawnfurt         22.330345  5.119541e+12          34.0
West Evan             27.013333  5.445616e+12           4.0
West Jefferyfurt      21.072857  3.614437e+12          65.0
West Kevintown        21.528571  7.002171e+12           5.0
West Oscar            24.280000  4.525743e+12          11.0
West Pamelaborough    33.799286  4.081521e+12          27.0
West Paulport         33.278235  4.895520e+12           5.0
West Peter            24.875484  4.630766e+12          61.0
West Sydneyhaven      22.368333  4.432234e+12          70.0
West Tony             29.609474  5.080147e+12          17.0
Williamchester        34.278182  5.679295e+12          26.0
Williamshire          26.990323  4.937704e+12          70.0
Wiseborough           22.676842  6.046575e+12          55.0
Yolandafurt           27.205500  4.870867e+12           7.0
Zimmermanmouth        28.301667  4.618734e+12          45.0

[125 rows x 3 columns]

In [ ]:
#creating the scatter plot:

fare_by_city



# The maximum x value for our chart will be 100
x_limit = 2450

# List of values from 0 to 100 each value being 1 greater than the last
x_axis = np.arange(0, x_limit, 1)

# Create a random array of data that we will use for our y values
data = [random.random() for value in x_axis]